config/routes.rb
  resources :task_contractors do
    collection do 
      post 'create_ajax'
      get 'autocomplete'
      get 'bulk_edit'
      post 'bulk_update'
      get 'context_menu'
    end
  end

app/models/task_contractor.rb
class TaskContractor < ActiveRecord::Base
  include Rails.application.routes.url_helpers
  include Redmine::SafeAttributes

  belongs_to :author, class_name: 'User'

  scope :visible, ->(*args) { where(TaskContractor.visible_condition(args.shift || User.current, *args)) }  
  scope :sorted, -> { order("#{table_name}.name ASC") }

  

  # Contractors are not scoped to projects, so we set project_key: '1'
  # to remove error while per project search
  acts_as_searchable columns: ["#{TaskContractor.table_name}.name"],
                     project_key: '1',
                     date_column: :created_at
  acts_as_customizable
  acts_as_attachable
  acts_as_activity_provider author_key: :author_id, timestamp: "#{table_name}.created_at"

  
  validates :author_id, presence: true
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  safe_attributes *%w[name custom_field_values custom_fields]

  after_create :send_create_notification
  after_update :send_update_notification

  def self.visible_condition(user, options = {})
    '1=1'
  end

  def self.css_icon
    'icon icon-user'
  end

  def editable_by?(user)
    editable?(user)
  end

  def project
    nil
  end

  def event_type
    'user'
  end

  def event_title
    name
  end

  def event_url
    task_contractor_path(self)
  end

  def description
    result = []
    custom_values.each do |cv|
      result.push("#{cv.custom_field.name}: #{cv.value}")
    end
    result.join(', ')
  end

  def event_description
    description
  end

  def event_datetime
    created_at
  end

  def visible?(user = nil)
    user ||= User.current
    user.allowed_to?(:view_task_contractors, project, global: true)
  end

  def editable?(user = nil)
    user ||= User.current
    user.allowed_to?(:manage_task_contractors, project, global: true)
  end

  def deletable?(user = nil)
    user ||= User.current
    user.allowed_to?(:manage_task_contractors, project, global: true)
  end

  def attachments_visible?(user = nil)
    visible?(user)
  end

  def attachments_editable?(user = nil)
    editable?(user)
  end

  def attachments_deletable?(user = nil)
    deletable?(user)
  end

  def to_s
    name
  end

  alias_attribute :created_on, :created_at
  alias_attribute :updated_on, :updated_at

  def notified_users
    if project
      project.notified_users.reject {|user| !visible?(user)}
    else
      [User.current]
    end
  end

  def send_create_notification
    # if Setting.notified_events.include?('task_contractor_added')
    notified_users.each do |user|
      TaskContractorMailer.task_contractor_added(user, self).deliver
    end
    # end
  end

  def send_update_notification
    # if Setting.notified_events.include?('task_contractor_updated')
    notified_users.each do |user|
      TaskContractorMailer.task_contractor_updated(user, self).deliver
    end
    # end
  end

end

app/controllers/task_contractors_controller.rb
class TaskContractorsController < ApplicationController

  menu_item :task_contractors

  before_action :authorize_global
  before_action :find_task_contractor, only: [:show, :edit, :update]
  before_action :find_task_contractors, only: [:context_menu, :bulk_edit, :bulk_update, :destroy]

  helper :task_contractors
  helper :custom_fields, :context_menus, :attachments, :issues
  include_query_helpers

  accept_api_auth :index, :show, :create, :update, :destroy

  def index
    retrieve_query(TaskContractorQuery)
    @entity_count = @query.task_contractors.count
    @entity_pages = Paginator.new @entity_count, per_page_option, params['page']
    @entities = @query.task_contractors(offset: @entity_pages.offset, limit: @entity_pages.per_page)
  end

  def show
    respond_to do |format|
      format.html
      format.api
      format.js
    end
  end

  def new
    @task_contractor = TaskContractor.new
    @task_contractor.safe_attributes = params[:task_contractor]

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @task_contractor = TaskContractor.new author: User.current
    @task_contractor.safe_attributes = params[:task_contractor]
    @task_contractor.save_attachments(params[:attachments] || (params[:task_contractor] && params[:task_contractor][:uploads]))

    respond_to do |format|
      if @task_contractor.save
        format.html do
          flash[:notice] = l(:notice_successful_create)
          redirect_back_or_default task_contractor_path(@task_contractor)
        end
        format.api { render action: 'show', status: :created, location: task_contractor_url(@task_contractor) }
        format.js { render template: 'common/close_modal' }
      else
        format.html { render action: 'new' }
        format.api { render_validation_errors(@task_contractor) }
        format.js { render action: 'new' }
      end
    end
  end

  def create_ajax
    @task_contractor = TaskContractor.find_by_name(params[:task_contractor][:name])
    if @task_contractor
      render json: @task_contractor
      return
    end
    @task_contractor = TaskContractor.new author: User.current
    @task_contractor.safe_attributes = params[:task_contractor]
    @task_contractor.save_attachments(params[:attachments] || (params[:task_contractor] && params[:task_contractor][:uploads]))

    if @task_contractor.save
      render json: @task_contractor
    else
      render_validation_errors(@task_contractor)
    end
  end


  def edit
    @task_contractor.safe_attributes = params[:task_contractor]

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @task_contractor.safe_attributes = params[:task_contractor]
    @task_contractor.save_attachments(params[:attachments] || (params[:task_contractor] && params[:task_contractor][:uploads]))

    respond_to do |format|
      if @task_contractor.save
        format.html do
          flash[:notice] = l(:notice_successful_update)
          redirect_back_or_default task_contractor_path(@task_contractor)
        end
        format.api { render_api_ok }
        format.js { render template: 'common/close_modal' }
      else
        format.html { render action: 'edit' }
        format.api { render_validation_errors(@task_contractor) }
        format.js { render action: 'edit' }
      end
    end
  end

  def destroy
    @task_contractors.each(&:destroy)

    respond_to do |format|
      format.html do
        flash[:notice] = l(:notice_successful_delete)
        redirect_back_or_default task_contractors_path
      end
      format.api { render_api_ok }
    end
  end

  def bulk_edit
  end

  def bulk_update
    unsaved, saved = [], []
    attributes = parse_params_for_bulk_update(params[:task_contractor])
    @task_contractors.each do |entity|
      entity.init_journal(User.current) if entity.respond_to? :init_journal
      entity.safe_attributes = attributes
      if entity.save
        saved << entity
      else
        unsaved << entity
      end
    end
    respond_to do |format|
      format.html do
        if unsaved.blank?
          flash[:notice] = l(:notice_successful_update)
        else
          flash[:error] = unsaved.map{|i| i.errors.full_messages}.flatten.uniq.join(",\n")
        end
        redirect_back_or_default :index
      end
    end
  end

  def context_menu
    if @task_contractors.size == 1
      @task_contractor = @task_contractors.first
    end

    can_edit = @task_contractors.detect{|c| !c.editable?}.nil?
    can_delete = @task_contractors.detect{|c| !c.deletable?}.nil?
    @can = {edit: can_edit, delete: can_delete}
    @back = back_url

    @task_contractor_ids, @safe_attributes, @selected = [], [], {}
    @task_contractors.each do |e|
      @task_contractor_ids << e.id
      @safe_attributes.concat e.safe_attribute_names
      attributes = e.safe_attribute_names - (%w(custom_field_values custom_fields))
      attributes.each do |c|
        column_name = c.to_sym
        if @selected.key? column_name
          @selected[column_name] = nil if @selected[column_name] != e.send(column_name)
        else
          @selected[column_name] = e.send(column_name)
        end
      end
    end

    @safe_attributes.uniq!

    render layout: false
  end

  def autocomplete
  end

  private

  def find_task_contractor
    @task_contractor = TaskContractor.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_task_contractors
    @task_contractors = TaskContractor.visible.where(id: (params[:id] || params[:ids])).to_a
    @task_contractor = @task_contractors.first if @task_contractors.count == 1
    raise ActiveRecord::RecordNotFound if @task_contractors.empty?
    raise Unauthorized unless @task_contractors.all?(&:visible?)

    @projects = @task_contractors.collect(&:project).compact.uniq
    @project = @projects.first if @projects.size == 1
  rescue ActiveRecord::RecordNotFound
    render_404
  end


end

app/helpers/task_contractors_helper.rb
module TaskContractorsHelper

end

app/views/task_contractors/_custom_field.html.erb
<p></p>

app/views/task_contractors/_form.html.erb
<%= labelled_form_for([@project, @task_contractor], html: { multipart: true, id: 'task_contractor_form', class: 'tabular', remote: request.xhr? }) do |f| %>
  <%= error_messages_for @task_contractor %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="box">
      <% if task_contractor.safe_attribute?('name') %>
      <p>
        <%= f.label :name, ::TaskContractor.human_attribute_name(:name) %>
        <%= f.text_field :name %>
      </p>
      <% end %>
      
      <% custom_field_values = task_contractor.visible_custom_field_values %>
      <% custom_field_values.each do |value| %>
      <p>
        <%= custom_field_tag_with_label :task_contractor, value %>
      </p>
      <% end %>
      <% if false %>
        <p id="attachments_form"><label><%= l(:label_attachment_plural) %></label><%= render :partial => 'attachments/form', :locals => {:container => task_contractor} %></p>
      <% end %>
  </div>

  <% if !request.xhr? %>
    <p>
      <% if f.object.new_record? %>
        <%= submit_tag l(:button_create), title: l(:button_create), class: "button-positive" %>
      <% else %>
        <%= submit_tag l(:button_update), title: l(:button_update), class: "button-positive" %>
      <% end %>
    </p>
  <% end %>
<% end %>

app/views/task_contractors/_list.html.erb
<%= form_tag({}, data: {cm_url: context_menu_task_contractors_path}) do %>
  <%= hidden_field_tag 'back_url', url_for(params: request.query_parameters), id: nil %>
  <div class="autoscroll">
    <table class="list odd-even entities">
      <thead>
        <tr>
          <th class="checkbox hide-when-print">
            <%= check_box_tag 'check_all', '', false, class: 'toggle-selection',
            title: "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
          </th>
          <% @query.inline_columns.each do |column| %>
            <%= column_header(@query, column) %>
          <% end %>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% grouped_query_results(entities, @query) do |entity, group_name, group_count, group_totals| %>
          <% if group_name %>
            <% reset_cycle %>
            <tr class="group open">
              <td colspan="<%= @query.inline_columns.size + 2 %>">
                <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
                <span class="name"><%= group_name %></span>
                <% if group_count %>
                <span class="count"><%= group_count %></span>
                <% end %>
                <span class="totals"><%= group_totals %></span>
                <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}",
                'toggleAllRowGroups(this)', class: 'toggle-all') %>
              </td>
            </tr>
          <% end %>
          <tr id="entity_id_<%= entity.id %>" class="entity <%= cycle('odd', 'even') %> hascontextmenu">
            <td class="checkbox hide-when-print"><%= check_box_tag('ids[]', entity.id, false, id: nil) %></td>
            <% @query.inline_columns.each do |column| %>
              <%= content_tag('td', column_content(column, entity), class: column.css_classes) %>
            <% end %>
            <td class="buttons">
              <% if entity.editable_by?(User.current) %>
              <%= link_to l(:button_edit), edit_task_contractor_path(entity),
                           title: l(:button_edit),
                           class: 'icon-only icon-edit' %>
              <%= link_to l(:button_delete), task_contractor_path(entity),
                           data: {confirm: l(:text_are_you_sure)},
                           method: :delete,
                           title: l(:button_delete),
                           class: 'icon-only icon-del' %>
              <% end %>
            </td>
          </tr>
          <% @query.block_columns.each do |column| %>
            <% if (text = column_content(column, entity)) && text.present? %>
              <tr class="<%= current_cycle %>">
                <td colspan="<%= @query.inline_columns.size + 1 %>" class="<%= column.css_classes %>">
                  <% if query.block_columns.count > 1 %>
                  <span><%= column.caption %></span>
                  <% end %>
                  <%= text %>
                </td>
              </tr>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<%= context_menu %>

app/views/task_contractors/_sidebar.html.erb
<ul>
  <% if @task_contractor && !@task_contractor.new_record? %>
    <%= content_tag(:li, link_to(l(:button_edit), edit_polymorphic_path([@project, @task_contractor]), title: l(:button_edit), class: 'icon icon-edit button')) %>
  <% end %>
  <% if @task_contractor.nil? %>
    <%= content_tag(:li, link_to(l(:button_task_contractor_new), new_polymorphic_path([@project, :task_contractor]), title: l(:title_task_contractor_new), class: 'icon icon-add button button-positive')) %>
  <% end %>
  <%= content_tag(:li, link_to(l(:label_task_contractors), polymorphic_path([@project, :task_contractors], set_filter: '1'), title: l(:label_task_contractors), class: 'icon icon-folder button')) %>
</ul>

app/views/task_contractors/context_menu.html.erb
<ul>
  <% if @task_contractor %>
    <li><%= context_menu_link l(:button_edit), edit_task_contractor_path(@task_contractor), class: 'icon icon-edit', disabled: !@can[:edit] %></li>
  <% end %>
  <% if @safe_attributes.include? 'status' %>
  <li class="folder">
    <a href="#" class="submenu icon icon-issue-status" onclick="return false;"><%= l(:field_status) %></a>
    <ul>
      <% TaskContractor.statuses.keys.each do |status| %>
        <li>
          <%= context_menu_link l("task_contractor.statuses.#{status}"), bulk_update_task_contractor_path(id: @task_contractor_ids, task_contractor: { status: status }, back_url: @back), method: :put, selected: (@selected[:status] == status), disabled: !@can[:edit], confirm: l(:text_are_you_sure) %>
        </li>
      <% end %>
    </ul>
  </li>
  <% end %>
  <li><%= context_menu_link l(:button_delete), task_contractor_path(id: @task_contractor_ids, back_url: @back), method: :delete, data: { confirm: l(:text_are_you_sure) }, class: 'icon icon-del', disabled: !@can[:delete] %></li>

  <%= call_hook(:view_task_contractors_context_menu_end, { task_contractor: @task_contractor, task_contractors: @task_contractors, can: @can, back: @back, project: @project }) %>
</ul>

app/views/task_contractors/edit.html.erb
<%= title l(:heading_task_contractor_edit) %>

<%= render partial: 'form', locals: { task_contractor: @task_contractor } %>

<% ### PAGE CUSTOMS ########################################################## %>
<% content_for :sidebar do %>
  <%= render partial: 'task_contractors/sidebar' %>
<% end %>

app/views/task_contractors/edit.js.erb
var modal = $("#ajax-modal");
modal.html("<%= j render(template: 'task_contractors/edit', formats: [:html]) %>");
showModal(modal.attr("id"));
var submitButton = {
  text:"<%=j l(:button_update) %>",
  title:"<%=j l(:button_update) %>",
  click: function() {$(this).find('form').submit()},
  'class': 'button-positive'
};
var closeButton = {
  text: "<%=j l(:button_close) %>",
  title: "<%=j l(:button_close) %>",
  click: function() {$(this).dialog('close');},
  'class': 'button'
};
modal.dialog('option', {
  buttons: [closeButton, submitButton]
});

app/views/task_contractors/index.html.erb
<div class="contextual">
  <% if User.current.allowed_to?(:add_task_contractors, @project, global: true) %>
    <%= link_to l(:button_task_contractor_new), new_task_contractor_path, class: 'icon icon-add' %>
  <% end %>
</div>
<h2><%= l(:label_task_contractors) %></h2>

<%= form_tag(task_contractors_path, method: :get, id: 'query_form') do %>
  <%= render partial: 'queries/query_form' %>
<% end %>

<% if @query.valid? %>
  <% if @entities.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
    <%= render_query_totals(@query) %>
    <%= render partial: 'list', locals: { entities: @entities }%>
    <span class="pagination"><%= pagination_links_full @entity_pages, @entity_count %></span>
  <% end %>
<% end %>

app/views/task_contractors/index.js.erb
var modal = $("#ajax-modal");
modal.html("<%= j render(template: 'task_contractors/index', formats: [:html]) %>");
showModal(modal.attr("id"));
var closeButton = {
  text: "<%=j l(:button_close) %>",
  title: "<%=j l(:button_close) %>",
  click: function() {$(this).dialog('close');},
  'class': 'button'
};
modal.dialog('option', {
  buttons: [closeButton, submitButton]
});

app/views/task_contractors/new.html.erb
<h3 class="title"><%= l(:heading_task_contractor_new) %></h3>

<%= render partial: 'form', locals: { task_contractor: @task_contractor } %>

<% ### PAGE CUSTOMS ########################################################## %>
<% content_for :sidebar do %>
  <%= render partial: 'task_contractors/sidebar' %>
<% end %>

app/views/task_contractors/new.js.erb
var modal = $("#ajax-modal");
modal.html("<%= j render(template: 'task_contractors/new', formats: [:html]) %>");

showModal(modal.attr("id"), '500px');
var submitButton = {
  text:"<%=j l(:button_create) %>",
  title:"<%=j l(:button_create) %>",
  click: function() {
    var form = $(this).find('form');
    var dialog = $(this);
    $.post(
      '/task_contractors/create_ajax',
      form.serialize(),
      function(data) {
        window.searchBoxResolve(data);
        dialog.dialog('close');
      }
    );
  },
  'class': 'button-positive'
};
var closeButton = {
  text: "<%=j l(:button_cancel) %>",
  title: "<%=j l(:button_cancel) %>",
  click: function() {$(this).dialog('close');},
  'class': 'button'
};
modal.dialog('option', {
  buttons: [closeButton, submitButton]
});


var form = modal.find('form');
form.on('keydown', function(event) {
  return event.key != "Enter";
});

app/views/task_contractors/show.html.erb
<%= title @task_contractor %>
<div class="issue">
  <table class="attributes">
    <%= render partial: 'redmine_extensions/custom_field_rows', locals: { custom_field_values: @task_contractor.visible_custom_field_values } %>
    <%= call_hook(:view_task_contractors_show_details_bottom, task_contractor: @task_contractor) %>
  </table>
  <% if @task_contractor.attachments.any? %>
    <hr />
    <%= link_to_attachments @task_contractor, thumbnails: true %>
  <% end %>
</div>
<% ### PAGE CUSTOMS ########################################################## %>
<% content_for :sidebar do %>
  <%= render partial: 'task_contractors/sidebar' %>
<% end %>

app/views/task_contractors/show.js.erb
var modal = $("#ajax-modal");
modal.html("<%= j render(template: 'task_contractors/show', formats: [:html]) %>");
showModal(modal.attr("id"));
var closeButton = {
  text: "<%=j l(:button_close) %>",
  title: "<%=j l(:button_close) %>",
  click: function() {$(this).dialog('close');},
  'class': 'button'
};
modal.dialog('option', {
  buttons: [closeButton, submitButton]
});